### ISSUE TITLE
How to get client indicators on botton 

### ISSUE THREAD

**Issue by AlephaNull** [chhajedji/dwm#1]
Pretty Good build. But how did you manage to get the activeindicatorbar patch to show on bottom instead of top
Thanks!

**Comment by chhajedji** [comment]
If you have applied the [activetagindicatorbar patch](https://dwm.suckless.org/patches/activetagindicatorbar), you can replace following line added by the patch 
```diff
+			drw_rect(drw, x + boxw, 0, w - ( 2 * boxw + 1), boxw,
+			    m == selmon && selmon->sel && selmon->sel->tags & 1 << i,
+			    urg & 1 << i);
```
with this line
```diff
+                       drw_rect(drw, x + boxw, bh - boxw/2, w - ( 2 * boxw + 1), boxw/2,
+                           m == selmon && selmon->sel && selmon->sel->tags & 1 << i,
+                           urg & 1 << i);

```
Actually only first line is different, second and third lines are same as in patch, but since they complete the `drw_rect` function call, I have listed them.

After this change, you should see highlighting like this
![image](https://user-images.githubusercontent.com/42715380/112745062-1ba31780-8fc3-11eb-9653-55a564a52e85.png)

**Comment by AlephaNull** [comment]
Thank you very much! It worked
